name: Pull Docker Image and SCA Scan
on:
  push:
    branches:
      - main
jobs:
  deploy-and-scan:
    name: Pull Docker Image and SCA Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Docker Image
        run: docker pull theecyberchef/dockerhub:myfirstimagepush